## this action just hangs

version: 1.0

description: higher-order workflow that allows retries for a provided action

input:
  - action
  - action_inputs: null
  - max_retries

vars:
  - retries: 0
  - failed: true

tasks:
  # must have an entry that isn't involved in the loop
  entry:
    action: core.noop
    next:
      - when: <% succeeded() %>
        do: call_action

  call_action:
    action: <% ctx().action %>
    input: <% ctx().action_inputs %>
    next:
      # todo: use succeeded() - ctx().failed is just for demo purposes
      - when: <% not ctx().failed %>
        do: finish
      # todo: use failed() - ctx().failed is just for demo purposes
      - when: <% ctx().failed %>
        do: try_again

  try_again:
    action: core.noop
    next:
      # if we haven't tried max times
      - when: <% ctx().retries < ctx().max_retries %>
        publish:
          - retries: <% ctx().retries + 1 %>
        do: call_action

      # if we have tried max times
      - when: <% ctx().failed and ctx().retries >= ctx().max_retries %>
        do: stop

      # hardcoded success at 3 tries
      - when: <% ctx().retries = 3 %>
        publish:
          - failed: false

  finish:
    action: core.echo message="Retry succeeded"

  stop:
    action: core.echo message="Exceeded retries"
    next:
      - do: fail